[spectrum]
amplitude = 5.0
windSpeed = 40.0
windDirection = [1.0, 1.0]
suppresorFactor = 1.0
length = 750.0
displacementScale = 22.0
choppinessScale = [11.0, 11.0]

[pbr]
sunDirection = [-1.29, -1.0, 4.86]
sunIrradiance = [1.0, 0.694, 0.32]
scatterColor = [0.016, 0.0836, 0.16]
bubbleColor = [0.0, 0.02, 0.1599]
bubbleDensity = 1.0
wavePeakScatterStrength = 1.0
scatterStrength = 1.0
scatterShadowStrength = 0.5
heightWave = 0.5
roughness = 0.08
envLightStrength = 1.0

[other]
tiling = 1
timeSpeed = 2.0
