[spectrum]
amplitude = 5.0
windSpeed = 35.0
windDirection = [1.0, 1.0]
suppressorFactor = 1.0
length = 750.0
displacementScale = 1.2
choppinessScale = [0.5, 0.7]

[pbr]
sunDirection = [-1.29, -1.0, 4.86]
sunColor = [1.0, 0.694, 0.32]
scatterColor = [0.016, 0.0836, 0.16]
bubbleColor = [0.0, 0.02, 0.1599]
bubbleDensity = 1.0
wavePeakScatterStrength = 1.0
scatterStrength = 1.0
scatterShadowStrength = 0.5
heightWave = 0.5
roughness = 0.08
envLightStrength = 1.0

[other]
tiling = 1
timeSpeed = 2.0
